idf_component_register(
    SRCS "main.c"
         "app_config.c"
         "app_config_model.c"
         "app_clock.c"
         "app_pet.c"
         "app_pet_model.c"
         "app_blehid.c"
         "app_blehid_keys.c"
         "app_portal.c"
         "app_store.c"
         "app_wifi.c"
         "ui_pixel.c"
         "ui_text.c"
         "ui_pixel_math.c"
         "fonts/font_cjk_20.c"
         "fonts/font_cjk_16.c"
         "demo_badge.c"
         "demo_settings.c"
         "demo_portal.c"
         "demo_display.c"
         "demo_button.c"
         "demo_audio.c"
         "demo_battery.c"
         "demo_radio.c"
         "demo_wifi.c"
         "demo_ble.c"
         "demo_hid.c"
         "demo_low_power.c"
    INCLUDE_DIRS "."
    REQUIRES bsp bt esp_event esp_hw_support esp_http_server esp_netif
             esp_timer esp_wifi fatfs json nvs_flash wear_levelling dns_server
)